version: '3'
services:
#mssql docker
  nextgame-sql:
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - nextgamenet

  nextgame-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:NextGame=Server=nextgame-sql,1433;Database=IB180082RSII;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5010:5010
    networks:
      - nextgamenet      
    links:
      - nextgame-sql
    depends_on:
      - nextgame-sql
      
networks:
  nextgamenet:
    driver: bridge     